baseURL                          = "https://www.insightful-s.com/"  # Your domain name. Must end with "/"
theme                            = "hugo-theme-introduction"
DefaultContentLanguage           = "es"                    # Default language for multilingual sites
# disqusshortname                 = ""                       # https://gohugo.io/content-management/comments
# googleAnalytics                = ""                       # https://gohugo.io/templates/internal/#google-analytics
# Ignore some files 
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    themeStyle                   = "dark"                 # Choose "light" or "dark"
    favicon                      = "/img/icon.png"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = false                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                  # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    # email                        = "javierbrolo@insightful-s.com"   # E-mail address for contact section
    # customCSS                    = ["foo.css"]             # Include custom css files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"                 # Input either "medium" or "large" or "fullheight"
        showLatest               = false                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 2                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = false                   # Show your current local time in contact section
        timeZone                 = "America/Guatemala"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    [params.projects]
        useTwoColumns            = true                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        googlePlus               = true
        pinterest                = true

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://twitter.com/insightful_s"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.facebook.com/insightful.s/"
        icon  = "facebook-f" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.instagram.com/insightful.s/"
        icon  = "instagram" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.youtube.com/channel/UCWv3MTKAmUV-z3H56kQkwXg/about"
        icon  = "youtube" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.linkedin.com/company/insightful-s/"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://github.com/InsightfulS-D3"
        icon  = "github" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:javierbrolo@insightful-s.com"  # For a direct email link, use "mailto:test@example.org".
        icon = "envelope" # icon name without the 'fa-'
        icon_pack = "fas"


# If you don't want to use the default menu, you can define one by yourself
[[menu.main]]
    name    = "Inicio"
    url     = "/"
    weight  = 1
[[menu.main]]
    name    = "Acerca de"
    url     = "/#about"
    weight  = 2
[[menu.main]]
    name    = "Servicios"
    url     = "/#Servicios"
    weight  = 3
[[menu.main]]
    name    = "Contacto"
    url     = "/#contact"
    weight  = 4

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "Insightful Solutions"
        [languages.en.params]
            description  = "Website Description"   # Max 160 characters show in search results
            # footerText   = ""                    # Text to override default footer text (markdown allowed)

    [languages.es]
        languageName     = "Español"
        languageCode     = "es"
        contentDir       = "content/es"
        weight           = 1
        title            = "Insightful Solutions"
        [languages.es.params]
            description  = "Descripcion del sitio web"
            footerText   = "(c) 2019 Insightful Solutions, S.A"


