baseURL                          = "https://www.insightful-s.com/"  # Your domain name. Must end with "/"
theme = "hugo-theme-introduction"
DefaultContentLanguage           = "es"                    # Default language for multilingual sites
# disqusshortname                 = ""                       # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                       # https://gohugo.io/templates/internal/#google-analytics
# Ignore some files 
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    themeStyle                   = "dark"                 # Choose "light" or "dark"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = true                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = true                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    # email                        = "javierbrolo@insightful-s.com"   # E-mail address for contact section
    # customCSS                    = ["foo.css"]             # Include custom css files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "medium"                 # Input either "medium" or "large" or "fullheight"
        showLatest               = false                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 1                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = false                    # Show your current local time in contact section
        timeZone                 = "America/Los_Angeles"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    [params.projects]
        useTwoColumns            = true                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        googlePlus               = true
        pinterest                = true

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://twitter.com/insightful_s"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.facebook.com/Insightful-Solutions-SA-372951870174638/"
        icon  = "facebook-f" # icon name without the 'fa-'
        icon_pack = "fab"
#    [[params.social]]
#        url   = "https://linkedin.com/"
#        icon  = "linkedin-in" # icon name without the 'fa-'
#        icon_pack = "fab"
    [[params.social]]
        url = "mailto:javierbrolo@insightful-s.com"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"


# If you don't want to use the default menu, you can define one by yourself
[[menu.main]]
    name    = "Inicio"
    url     = "/"
    weight  = 1
[[menu.main]]
    name    = "Acerca de"
    url     = "/#about"
    weight  = 2
[[menu.main]]
    name    = "Proyectos"
    url     = "/#proyectos"
    weight  = 3
[[menu.main]]
    name    = "Contacto"
    url     = "/#contact"
    weight  = 4

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "Introduction"
        [languages.en.params]
            description  = "Website Description"   # Max 160 characters show in search results
            # footerText   = ""                      # Text to override default footer text (markdown allowed)

    [languages.es]
        languageName     = "Español"
        languageCode     = "es"
        contentDir       = "content/es"
        weight           = 1
        title            = "Introducción"
        [languages.es.params]
            description  = "Descripcion del sitio web"
            # footerText   = ""

    [languages.de]
        languageName     = "Deutsch"
        languageCode     = "de"
        contentDir       = "content/de"
        weight           = 2
        title            = "Vorstellung"
        [languages.de.params]
            dateFormat   = "2. January 2006"
            description  = "Beschreibung der Webseite"
            # footerText   = ""
